### ISSUE TITLE
基于 redis 的实现会受缓存淘汰策略影响吗

### ISSUE THREAD

**Issue by DZGodly** [yedf/dtmcli#1]
barrier_redis.go 文件中给出了基于 redis 的实现，里面用到了多个键值对存数据，都有过期时间。
那么在 redis 内存吃紧的情况下，其中的某个 key 会被 redis 淘汰掉吧，这种情况下事务流程也会收到影响吧

**Comment by yedf2** [comment]
当然会受到影响，你就用常规的办法解决就行了，例如单独一个redis做相关的业务，保证不会过期前淘汰

**Comment by DZGodly** [comment]
> 当然会受到影响，你就用常规的办法解决就行了，例如单独一个redis做相关的业务，保证不会过期前淘汰

好的，感谢👍
