### ISSUE TITLE
有考虑制作C++的SDK吗

### ISSUE THREAD

**Issue by kamikyo** [yedf/dtmcli#2]
有考虑制作C++的SDK吗？或者可否使用纯http的交互形式，这样就可以使用c++来与DTM进行交互了

**Comment by yedf2** [comment]
dtm支持http，所以用纯http来使用dtm是完全可以的

c++的业务场景用得比较少，目前没有把这个客户端作为高优先级来做。如果社区同学愿意贡献，我们是非常欢迎的

**Comment by kamikyo** [comment]
感谢您的回复，那我再去研究研究纯http的交互方式。因为我在官方文上看到http的交互使用了一个dtmcli的工具，我以为并没有纯http交互机制
